# Generated by Django 5.0.7 on 2024-08-09 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
    ]
